const TabConstants = {
  PROFILE: "P",

  DASHBOARD_OVERVIEW: "DO",
  DASHBOARD_PROFILE: "DP",
  DASHBOARD_MENU: "DM",
  DASHBOARD_SETTINGS: "DS",
  DASHBOARD_FEEDBACKS: "DF",
  DASHBOARD_SUBSCRIPTIONS: "DSUB",
  DASHBOARD_ORDERS: "DOR",
  DASHBOARD_EMPLOYEES: "DE",

  USER_ORDERS: "UOR"

};
export default TabConstants;
